"""add conversation_memory

Revision ID: 03cc579067f2
Revises: f26eb22b3f29
Create Date: 2026-03-14 11:59:35.633985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '03cc579067f2'
down_revision: Union[str, Sequence[str], None] = 'f26eb22b3f29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_memories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(length=50), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_memories_id'), 'conversation_memories', ['id'], unique=False)
    op.create_index(op.f('ix_conversation_memories_phone_number'), 'conversation_memories', ['phone_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversation_memories_phone_number'), table_name='conversation_memories')
    op.drop_index(op.f('ix_conversation_memories_id'), table_name='conversation_memories')
    op.drop_table('conversation_memories')
    # ### end Alembic commands ###
