"""enable_cascading_deletes

Revision ID: 1ad08eebf8aa
Revises: bbe26bb415c3
Create Date: 2026-03-05 12:03:57.963338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ad08eebf8aa'
down_revision: Union[str, Sequence[str], None] = 'bbe26bb415c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
