"""remove product_id from knowledge_entries

Revision ID: 22aeb1c7ff3a
Revises: a2c3d4e5f6g7
Create Date: 2026-03-17 09:38:21.881271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '22aeb1c7ff3a'
down_revision: Union[str, Sequence[str], None] = 'a2c3d4e5f6g7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('knowledge_entries', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index(op.f('ix_knowledge_entries_product_id'), table_name='knowledge_entries')
    op.drop_constraint(op.f('knowledge_entries_product_id_fkey'), 'knowledge_entries', type_='foreignkey')
    op.drop_column('knowledge_entries', 'product_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_entries', sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('knowledge_entries_product_id_fkey'), 'knowledge_entries', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_knowledge_entries_product_id'), 'knowledge_entries', ['product_id'], unique=False)
    op.alter_column('knowledge_entries', 'metadata',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    # ### end Alembic commands ###
