"""add company_id to knowledge_entries

Revision ID: 2f901c6c795e
Revises: 20260227_add_brand_company_id
Create Date: 2026-02-28 12:08:44.202521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f901c6c795e'
down_revision: Union[str, None] = '20260227_add_brand_company_id'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_entries', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_knowledge_entries_company_id'), 'knowledge_entries', ['company_id'], unique=False)
    op.create_foreign_key(None, 'knowledge_entries', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'knowledge_entries', type_='foreignkey')
    op.drop_index(op.f('ix_knowledge_entries_company_id'), table_name='knowledge_entries')
    op.drop_column('knowledge_entries', 'company_id')
    # ### end Alembic commands ###
