"""Add missing columns to audit_logs

Revision ID: 350e6874ef31
Revises: 2f901c6c795e
Create Date: 2026-03-01 07:00:23.334401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '350e6874ef31'
down_revision: Union[str, Sequence[str], None] = '2f901c6c795e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('call_states',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('call_session_id', sa.Integer(), nullable=False),
    sa.Column('state', sa.Enum('INCOMING', 'GREETING', 'PROFILING', 'PROBLEM', 'ADVISORY', 'ESCALATED', 'CLOSURE', 'ENDED', name='statetype'), nullable=False),
    sa.Column('entered_at', sa.DateTime(), nullable=False),
    sa.Column('exited_at', sa.DateTime(), nullable=True),
    sa.Column('state_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['call_session_id'], ['call_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_call_states_session', 'call_states', ['call_session_id'], unique=False)
    op.create_index('idx_call_states_state', 'call_states', ['state'], unique=False)
    op.create_table('farmer_queries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('call_session_id', sa.Integer(), nullable=False),
    sa.Column('farmer_id', sa.Integer(), nullable=True),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('intent', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['call_session_id'], ['call_sessions.id'], ),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_call_session_id', 'farmer_queries', ['call_session_id'], unique=False)
    op.create_index('ix_farmer_id', 'farmer_queries', ['farmer_id'], unique=False)
    op.create_index('ix_organisation_id', 'farmer_queries', ['organisation_id'], unique=False)
    op.drop_table('organisation_settings')
    op.drop_index(op.f('checkpoint_blobs_thread_id_idx'), table_name='checkpoint_blobs')
    op.drop_table('checkpoint_blobs')
    op.drop_index(op.f('checkpoint_writes_thread_id_idx'), table_name='checkpoint_writes')
    op.drop_table('checkpoint_writes')
    op.drop_index(op.f('idx_confidence_rules_org'), table_name='confidence_rules')
    op.drop_table('confidence_rules')
    op.drop_table('checkpoint_migrations')
    op.drop_index(op.f('idx_expert_actions_escalation'), table_name='expert_actions')
    op.drop_index(op.f('idx_expert_actions_expert'), table_name='expert_actions')
    op.drop_table('expert_actions')
    op.drop_index(op.f('checkpoints_thread_id_idx'), table_name='checkpoints')
    op.drop_table('checkpoints')
    op.add_column('audit_logs', sa.Column('username', sa.String(length=100), nullable=False))
    op.add_column('audit_logs', sa.Column('user_role', sa.String(length=50), nullable=False))
    op.add_column('audit_logs', sa.Column('description', sa.Text(), nullable=False))
    op.add_column('audit_logs', sa.Column('organisation_id', sa.Integer(), nullable=True))
    op.alter_column('audit_logs', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('audit_logs', 'entity_id',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('audit_logs', 'severity',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'info'::character varying"))
    op.drop_index(op.f('idx_audit_category'), table_name='audit_logs')
    op.drop_index(op.f('idx_audit_severity'), table_name='audit_logs')
    op.drop_index(op.f('idx_audit_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('idx_audit_user'), table_name='audit_logs')
    op.create_index(op.f('ix_audit_logs_action_category'), 'audit_logs', ['action_category'], unique=False)
    op.create_index(op.f('ix_audit_logs_action_type'), 'audit_logs', ['action_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_organisation_id'), 'audit_logs', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.drop_constraint(op.f('audit_logs_user_id_fkey'), 'audit_logs', type_='foreignkey')
    op.alter_column('banned_products', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_index(op.f('idx_banned_active'), table_name='banned_products')
    op.drop_index(op.f('idx_banned_product_name'), table_name='banned_products')
    op.create_index(op.f('ix_banned_products_id'), 'banned_products', ['id'], unique=False)
    op.create_index(op.f('ix_banned_products_product_name'), 'banned_products', ['product_name'], unique=False)
    op.drop_constraint(op.f('banned_products_banned_by_user_id_fkey'), 'banned_products', type_='foreignkey')
    op.drop_index(op.f('idx_brands_org_id'), table_name='brands')
    op.alter_column('call_metrics', 'states_visited',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('call_metrics', 'call_outcome',
               existing_type=postgresql.ENUM('COMPLETED', 'ABANDONED', 'ESCALATED', 'FAILED', 'CALLBACK_SCHEDULED', name='call_outcome_enum'),
               type_=sa.Enum('COMPLETED', 'ABANDONED', 'ESCALATED', 'FAILED', 'CALLBACK_SCHEDULED', name='calloutcome'),
               existing_nullable=True)
    op.drop_index(op.f('idx_call_sessions_org_id'), table_name='call_sessions')
    op.drop_column('call_sessions', 'advisory_text')
    op.drop_column('call_sessions', 'raw_advisory')
    op.drop_column('call_sessions', 'advisory_generated')
    op.alter_column('call_summaries', 'key_recommendations',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('call_summaries', 'products_mentioned',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('call_transcripts', 'speaker',
               existing_type=postgresql.ENUM('AI', 'FARMER', 'EXPERT', name='speaker_enum'),
               type_=sa.Enum('AI', 'FARMER', 'EXPERT', name='speaker'),
               existing_nullable=False)
    op.alter_column('cases', 'organisation_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index('idx_case_org_status', 'cases', ['organisation_id', 'status'], unique=False)
    op.drop_column('cases', 'affected_area_acres')
    op.drop_column('cases', 'crop_stage')
    op.alter_column('companies', 'max_operators',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Max company users allowed',
               existing_nullable=True)
    op.drop_constraint(op.f('escalations_organisation_id_fkey'), 'escalations', type_='foreignkey')
    op.drop_column('escalations', 'organisation_id')
    op.add_column('farmer_questions', sa.Column('organisation_id', sa.Integer(), nullable=False))
    op.add_column('farmer_questions', sa.Column('company_id', sa.Integer(), nullable=False))
    op.alter_column('farmer_questions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.create_index(op.f('ix_farmer_questions_id'), 'farmer_questions', ['id'], unique=False)
    op.create_foreign_key(None, 'farmer_questions', 'organisations', ['organisation_id'], ['id'])
    op.create_foreign_key(None, 'farmer_questions', 'companies', ['company_id'], ['id'])
    op.alter_column('farmers', 'organisation_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('farmers', 'crop_age_days',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.drop_index(op.f('idx_farmers_org_id'), table_name='farmers')
    op.drop_index(op.f('ix_farmers_phone_number'), table_name='farmers')
    op.create_index('idx_farmer_org_phone', 'farmers', ['organisation_id', 'phone_number'], unique=False)
    op.create_unique_constraint('uix_org_phone', 'farmers', ['organisation_id', 'phone_number'])
    op.drop_index(op.f('idx_kb_entries_org_id'), table_name='kb_entries')
    op.drop_constraint(op.f('kb_entries_organisation_id_fkey'), 'kb_entries', type_='foreignkey')
    op.create_foreign_key(None, 'kb_entries', 'organisations', ['organisation_id'], ['id'])
    op.drop_column('kb_entries', 'embedding_model')
    op.drop_column('kb_entries', 'last_embedded_at')
    op.drop_column('kb_entries', 'embedding_id')
    op.alter_column('organisation_kb_files', 'uploaded_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('organisation_kb_files', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.create_index(op.f('ix_organisation_kb_files_id'), 'organisation_kb_files', ['id'], unique=False)
    op.drop_constraint(op.f('organisation_phone_numbers_phone_number_key'), 'organisation_phone_numbers', type_='unique')
    op.drop_index(op.f('idx_org_primary_phone'), table_name='organisations')
    op.drop_constraint(op.f('organisations_primary_phone_key'), 'organisations', type_='unique')
    op.create_unique_constraint(None, 'organisations', ['email'])
    op.drop_column('organisations', 'phone_numbers')
    op.add_column('platform_config', sa.Column('rag_strictness_level', sa.String(length=20), nullable=True))
    op.add_column('platform_config', sa.Column('rag_min_confidence', sa.Integer(), nullable=True))
    op.add_column('platform_config', sa.Column('rag_max_results', sa.Integer(), nullable=True))
    op.add_column('platform_config', sa.Column('force_kb_approval', sa.Boolean(), nullable=True))
    op.add_column('platform_config', sa.Column('enable_call_recording', sa.Boolean(), nullable=True))
    op.add_column('platform_config', sa.Column('enable_auto_escalation', sa.Boolean(), nullable=True))
    op.add_column('platform_config', sa.Column('trial_duration_days', sa.Integer(), nullable=True))
    op.add_column('platform_config', sa.Column('max_concurrent_calls', sa.Integer(), nullable=True))
    op.add_column('platform_config', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.alter_column('platform_config', 'ai_confidence_threshold',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               nullable=True,
               existing_server_default=sa.text("'0.7'::double precision"))
    op.alter_column('platform_config', 'max_call_duration_minutes',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('30'))
    op.alter_column('platform_config', 'default_language',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               existing_server_default=sa.text("'hi'::character varying"))
    op.alter_column('platform_config', 'stt_provider',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'google'::character varying"))
    op.alter_column('platform_config', 'tts_provider',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'google'::character varying"))
    op.alter_column('platform_config', 'llm_model',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               existing_server_default=sa.text("'gpt-4'::character varying"))
    op.alter_column('platform_config', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(op.f('platform_config_updated_by_user_id_fkey'), 'platform_config', type_='foreignkey')
    op.drop_column('platform_config', 'rag_enabled')
    op.drop_column('platform_config', 'auto_escalate_low_confidence')
    op.drop_column('platform_config', 'rag_top_k')
    op.drop_column('platform_config', 'enable_product_safety_check')
    op.drop_column('platform_config', 'updated_by_user_id')
    op.drop_column('platform_config', 'min_confidence_for_product_recommendation')
    op.drop_index(op.f('idx_products_org_id'), table_name='products')
    op.drop_column('products', 'approved_at')
    op.drop_column('products', 'approval_status')
    op.drop_column('products', 'ban_reason')
    op.drop_column('products', 'approved_by')
    op.drop_index(op.f('idx_users_org_id'), table_name='users')
    op.drop_constraint(op.f('users_organisation_id_fkey'), 'users', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('users_organisation_id_fkey'), 'users', 'organisations', ['organisation_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('idx_users_org_id'), 'users', ['organisation_id'], unique=False)
    op.add_column('products', sa.Column('approved_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('ban_reason', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('approval_status', postgresql.ENUM('pending', 'approved', 'banned', name='approval_status_enum'), server_default=sa.text("'pending'::approval_status_enum"), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('approved_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_index(op.f('idx_products_org_id'), 'products', ['organisation_id'], unique=False)
    op.add_column('platform_config', sa.Column('min_confidence_for_product_recommendation', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0.8'::double precision"), autoincrement=False, nullable=False))
    op.add_column('platform_config', sa.Column('updated_by_user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('platform_config', sa.Column('enable_product_safety_check', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.add_column('platform_config', sa.Column('rag_top_k', sa.INTEGER(), server_default=sa.text('5'), autoincrement=False, nullable=False))
    op.add_column('platform_config', sa.Column('auto_escalate_low_confidence', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.add_column('platform_config', sa.Column('rag_enabled', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('platform_config_updated_by_user_id_fkey'), 'platform_config', 'users', ['updated_by_user_id'], ['id'], ondelete='SET NULL')
    op.alter_column('platform_config', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('platform_config', 'llm_model',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               existing_server_default=sa.text("'gpt-4'::character varying"))
    op.alter_column('platform_config', 'tts_provider',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'google'::character varying"))
    op.alter_column('platform_config', 'stt_provider',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'google'::character varying"))
    op.alter_column('platform_config', 'default_language',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               existing_server_default=sa.text("'hi'::character varying"))
    op.alter_column('platform_config', 'max_call_duration_minutes',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('30'))
    op.alter_column('platform_config', 'ai_confidence_threshold',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text("'0.7'::double precision"))
    op.drop_column('platform_config', 'updated_by')
    op.drop_column('platform_config', 'max_concurrent_calls')
    op.drop_column('platform_config', 'trial_duration_days')
    op.drop_column('platform_config', 'enable_auto_escalation')
    op.drop_column('platform_config', 'enable_call_recording')
    op.drop_column('platform_config', 'force_kb_approval')
    op.drop_column('platform_config', 'rag_max_results')
    op.drop_column('platform_config', 'rag_min_confidence')
    op.drop_column('platform_config', 'rag_strictness_level')
    op.add_column('organisations', sa.Column('phone_numbers', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'organisations', type_='unique')
    op.create_unique_constraint(op.f('organisations_primary_phone_key'), 'organisations', ['primary_phone'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_org_primary_phone'), 'organisations', ['primary_phone'], unique=False)
    op.create_unique_constraint(op.f('organisation_phone_numbers_phone_number_key'), 'organisation_phone_numbers', ['phone_number'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_organisation_kb_files_id'), table_name='organisation_kb_files')
    op.alter_column('organisation_kb_files', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('organisation_kb_files', 'uploaded_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.add_column('kb_entries', sa.Column('embedding_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('kb_entries', sa.Column('last_embedded_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('kb_entries', sa.Column('embedding_model', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'kb_entries', type_='foreignkey')
    op.create_foreign_key(op.f('kb_entries_organisation_id_fkey'), 'kb_entries', 'organisations', ['organisation_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_kb_entries_org_id'), 'kb_entries', ['organisation_id'], unique=False)
    op.drop_constraint('uix_org_phone', 'farmers', type_='unique')
    op.drop_index('idx_farmer_org_phone', table_name='farmers')
    op.create_index(op.f('ix_farmers_phone_number'), 'farmers', ['phone_number'], unique=True)
    op.create_index(op.f('idx_farmers_org_id'), 'farmers', ['organisation_id'], unique=False)
    op.alter_column('farmers', 'crop_age_days',
               existing_type=sa.String(length=200),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('farmers', 'organisation_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'farmer_questions', type_='foreignkey')
    op.drop_constraint(None, 'farmer_questions', type_='foreignkey')
    op.drop_index(op.f('ix_farmer_questions_id'), table_name='farmer_questions')
    op.alter_column('farmer_questions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_column('farmer_questions', 'company_id')
    op.drop_column('farmer_questions', 'organisation_id')
    op.add_column('escalations', sa.Column('organisation_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('escalations_organisation_id_fkey'), 'escalations', 'organisations', ['organisation_id'], ['id'], ondelete='CASCADE')
    op.alter_column('companies', 'max_operators',
               existing_type=sa.INTEGER(),
               comment='Max company users allowed',
               existing_nullable=True)
    op.add_column('cases', sa.Column('crop_stage', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('cases', sa.Column('affected_area_acres', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_index('idx_case_org_status', table_name='cases')
    op.alter_column('cases', 'organisation_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('call_transcripts', 'speaker',
               existing_type=sa.Enum('AI', 'FARMER', 'EXPERT', name='speaker'),
               type_=postgresql.ENUM('AI', 'FARMER', 'EXPERT', name='speaker_enum'),
               existing_nullable=False)
    op.alter_column('call_summaries', 'products_mentioned',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('call_summaries', 'key_recommendations',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.add_column('call_sessions', sa.Column('advisory_generated', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('call_sessions', sa.Column('raw_advisory', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('call_sessions', sa.Column('advisory_text', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_index(op.f('idx_call_sessions_org_id'), 'call_sessions', ['organisation_id'], unique=False)
    op.alter_column('call_metrics', 'call_outcome',
               existing_type=sa.Enum('COMPLETED', 'ABANDONED', 'ESCALATED', 'FAILED', 'CALLBACK_SCHEDULED', name='calloutcome'),
               type_=postgresql.ENUM('COMPLETED', 'ABANDONED', 'ESCALATED', 'FAILED', 'CALLBACK_SCHEDULED', name='call_outcome_enum'),
               existing_nullable=True)
    op.alter_column('call_metrics', 'states_visited',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.create_index(op.f('idx_brands_org_id'), 'brands', ['organisation_id'], unique=False)
    op.create_foreign_key(op.f('banned_products_banned_by_user_id_fkey'), 'banned_products', 'users', ['banned_by_user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_banned_products_product_name'), table_name='banned_products')
    op.drop_index(op.f('ix_banned_products_id'), table_name='banned_products')
    op.create_index(op.f('idx_banned_product_name'), 'banned_products', ['product_name'], unique=False)
    op.create_index(op.f('idx_banned_active'), 'banned_products', ['is_active'], unique=False)
    op.alter_column('banned_products', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.create_foreign_key(op.f('audit_logs_user_id_fkey'), 'audit_logs', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_organisation_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action_category'), table_name='audit_logs')
    op.create_index(op.f('idx_audit_user'), 'audit_logs', ['user_id'], unique=False)
    op.create_index(op.f('idx_audit_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_index(op.f('idx_audit_severity'), 'audit_logs', ['severity'], unique=False)
    op.create_index(op.f('idx_audit_category'), 'audit_logs', ['action_category'], unique=False)
    op.alter_column('audit_logs', 'severity',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'info'::character varying"))
    op.alter_column('audit_logs', 'entity_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('audit_logs', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('audit_logs', 'organisation_id')
    op.drop_column('audit_logs', 'description')
    op.drop_column('audit_logs', 'user_role')
    op.drop_column('audit_logs', 'username')
    op.create_table('checkpoints',
    sa.Column('thread_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('checkpoint_ns', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('checkpoint_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('parent_checkpoint_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('checkpoint', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'checkpoint_id', name=op.f('checkpoints_pkey'))
    )
    op.create_index(op.f('checkpoints_thread_id_idx'), 'checkpoints', ['thread_id'], unique=False)
    op.create_table('expert_actions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('escalation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('expert_user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('action_type', postgresql.ENUM('VIEWED', 'ASSIGNED', 'NOTES_ADDED', 'ADVISORY_PROVIDED', 'CALLBACK_SCHEDULED', 'RESOLVED', 'REOPENED', name='expert_action_enum'), autoincrement=False, nullable=False),
    sa.Column('action_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('time_spent_seconds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['escalation_id'], ['escalations.id'], name=op.f('expert_actions_escalation_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['expert_user_id'], ['users.id'], name=op.f('expert_actions_expert_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('expert_actions_pkey'))
    )
    op.create_index(op.f('idx_expert_actions_expert'), 'expert_actions', ['expert_user_id'], unique=False)
    op.create_index(op.f('idx_expert_actions_escalation'), 'expert_actions', ['escalation_id'], unique=False)
    op.create_table('checkpoint_migrations',
    sa.Column('v', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('v', name=op.f('checkpoint_migrations_pkey'))
    )
    op.create_table('confidence_rules',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('organisation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rule_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('rule_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('threshold_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('escalation_reason', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('priority_boost', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], name=op.f('confidence_rules_organisation_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('confidence_rules_pkey'))
    )
    op.create_index(op.f('idx_confidence_rules_org'), 'confidence_rules', ['organisation_id'], unique=False)
    op.create_table('checkpoint_writes',
    sa.Column('thread_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('checkpoint_ns', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('checkpoint_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('task_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('idx', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('channel', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('blob', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('task_path', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'checkpoint_id', 'task_id', 'idx', name=op.f('checkpoint_writes_pkey'))
    )
    op.create_index(op.f('checkpoint_writes_thread_id_idx'), 'checkpoint_writes', ['thread_id'], unique=False)
    op.create_table('checkpoint_blobs',
    sa.Column('thread_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('checkpoint_ns', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('channel', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('version', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('blob', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'channel', 'version', name=op.f('checkpoint_blobs_pkey'))
    )
    op.create_index(op.f('checkpoint_blobs_thread_id_idx'), 'checkpoint_blobs', ['thread_id'], unique=False)
    op.create_table('organisation_settings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('organisation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ai_model', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('default_language', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('supported_languages', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('crop_focus', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('monthly_call_limit', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('features_enabled', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ai_prompt_template', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], name=op.f('organisation_settings_organisation_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('organisation_settings_pkey')),
    sa.UniqueConstraint('organisation_id', name=op.f('organisation_settings_organisation_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_index('ix_organisation_id', table_name='farmer_queries')
    op.drop_index('ix_farmer_id', table_name='farmer_queries')
    op.drop_index('ix_call_session_id', table_name='farmer_queries')
    op.drop_table('farmer_queries')
    op.drop_index('idx_call_states_state', table_name='call_states')
    op.drop_index('idx_call_states_session', table_name='call_states')
    op.drop_table('call_states')
    # ### end Alembic commands ###
