"""001_consolidated_initial

Revision ID: 36c49fef3e8e
Revises: 
Create Date: 2026-03-04 13:30:12.937948

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy

revision: str = '36c49fef3e8e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('user_role', sa.String(length=50), nullable=False),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('action_category', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('organisation_id', sa.Integer(), nullable=True),
    sa.Column('old_value', sa.JSON(), nullable=True),
    sa.Column('new_value', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action_category'), 'audit_logs', ['action_category'], unique=False)
    op.create_index(op.f('ix_audit_logs_action_type'), 'audit_logs', ['action_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_organisation_id'), 'audit_logs', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('banned_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=200), nullable=False),
    sa.Column('chemical_name', sa.String(length=200), nullable=True),
    sa.Column('ban_reason', sa.Text(), nullable=False),
    sa.Column('regulatory_reference', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('banned_by_user_id', sa.Integer(), nullable=False),
    sa.Column('banned_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_banned_products_id'), 'banned_products', ['id'], unique=False)
    op.create_index(op.f('ix_banned_products_product_name'), 'banned_products', ['product_name'], unique=False)
    op.create_table('farmers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('village', sa.String(length=200), nullable=True),
    sa.Column('district', sa.String(length=200), nullable=True),
    sa.Column('state', sa.String(length=200), nullable=True),
    sa.Column('crop_type', sa.String(length=200), nullable=True),
    sa.Column('land_size', sa.String(length=50), nullable=True),
    sa.Column('crop_area', sa.String(length=100), nullable=True),
    sa.Column('problem_area', sa.String(length=200), nullable=True),
    sa.Column('crop_age_days', sa.String(length=200), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='farmerstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_farmers_id'), 'farmers', ['id'], unique=False)
    op.create_index(op.f('ix_farmers_phone_number'), 'farmers', ['phone_number'], unique=False)
    op.create_table('organisations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('plan_type', sa.String(length=50), nullable=False),
    sa.Column('phone_numbers', sa.String(length=20), nullable=True),
    sa.Column('secondary_phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('pincode', sa.String(length=10), nullable=True),
    sa.Column('website_link', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_organisations_id'), 'organisations', ['id'], unique=False)
    op.create_table('platform_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ai_confidence_threshold', sa.Integer(), nullable=True),
    sa.Column('max_call_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('default_language', sa.String(length=10), nullable=True),
    sa.Column('stt_provider', sa.String(length=50), nullable=True),
    sa.Column('tts_provider', sa.String(length=50), nullable=True),
    sa.Column('llm_model', sa.String(length=100), nullable=True),
    sa.Column('rag_strictness_level', sa.String(length=20), nullable=True),
    sa.Column('rag_min_confidence', sa.Integer(), nullable=True),
    sa.Column('rag_max_results', sa.Integer(), nullable=True),
    sa.Column('force_kb_approval', sa.Boolean(), nullable=True),
    sa.Column('enable_call_recording', sa.Boolean(), nullable=True),
    sa.Column('enable_auto_escalation', sa.Boolean(), nullable=True),
    sa.Column('trial_duration_days', sa.Integer(), nullable=True),
    sa.Column('max_concurrent_calls', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('call_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('farmer_id', sa.Integer(), nullable=True),
    sa.Column('phone_number', sa.String(length=15), nullable=False),
    sa.Column('provider_name', sa.String(length=50), nullable=True),
    sa.Column('provider_call_id', sa.String(length=200), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'FAILED', name='callstatus'), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('organisation_id', sa.Integer(), nullable=True),
    sa.Column('from_phone', sa.String(length=20), nullable=True),
    sa.Column('to_phone', sa.String(length=20), nullable=True),
    sa.Column('exotel_call_sid', sa.String(length=100), nullable=True),
    sa.Column('call_direction', sa.Enum('inbound', 'outbound', name='call_direction_enum'), nullable=True),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_call_sessions_id'), 'call_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_call_sessions_session_id'), 'call_sessions', ['session_id'], unique=True)
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('business_type', sa.String(length=100), nullable=True),
    sa.Column('brand_name', sa.String(length=200), nullable=True),
    sa.Column('contact_person', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('secondary_phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('pincode', sa.String(length=10), nullable=True),
    sa.Column('website_link', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('gst_number', sa.String(length=50), nullable=True),
    sa.Column('registration_number', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('max_operators', sa.Integer(), server_default='5', nullable=False),
    sa.Column('max_products', sa.Integer(), server_default='100', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    op.create_index(op.f('ix_companies_organisation_id'), 'companies', ['organisation_id'], unique=False)
    op.create_table('kb_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('crop_name', sa.String(length=100), nullable=True),
    sa.Column('problem_type', sa.String(length=100), nullable=True),
    sa.Column('solution_steps', sa.Text(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('is_banned', sa.Boolean(), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kb_entries_id'), 'kb_entries', ['id'], unique=False)
    op.create_index(op.f('ix_kb_entries_organisation_id'), 'kb_entries', ['organisation_id'], unique=False)
    op.create_table('organisation_phone_numbers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_phone_active_lookup', 'organisation_phone_numbers', ['phone_number', 'is_active'], unique=False)
    op.create_index(op.f('ix_organisation_phone_numbers_id'), 'organisation_phone_numbers', ['id'], unique=False)
    op.create_index(op.f('ix_organisation_phone_numbers_organisation_id'), 'organisation_phone_numbers', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_organisation_phone_numbers_phone_number'), 'organisation_phone_numbers', ['phone_number'], unique=True)
    op.create_table('brands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brands_company_id'), 'brands', ['company_id'], unique=False)
    op.create_index(op.f('ix_brands_id'), 'brands', ['id'], unique=False)
    op.create_index(op.f('ix_brands_organisation_id'), 'brands', ['organisation_id'], unique=False)
    op.create_table('call_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('call_session_id', sa.Integer(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('total_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('states_visited', sa.JSON(), nullable=True),
    sa.Column('profiling_questions_completed', sa.Integer(), nullable=True),
    sa.Column('symptoms_detected', sa.Integer(), nullable=True),
    sa.Column('kb_entries_retrieved', sa.Integer(), nullable=True),
    sa.Column('advisory_confidence', sa.Float(), nullable=True),
    sa.Column('was_escalated', sa.Boolean(), nullable=True),
    sa.Column('escalation_reason', sa.String(length=255), nullable=True),
    sa.Column('farmer_satisfaction', sa.Integer(), nullable=True),
    sa.Column('call_outcome', sa.Enum('COMPLETED', 'ABANDONED', 'ESCALATED', 'FAILED', 'CALLBACK_SCHEDULED', name='calloutcome'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['call_session_id'], ['call_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_call_metrics_call', 'call_metrics', ['call_session_id'], unique=False)
    op.create_index('idx_call_metrics_org', 'call_metrics', ['organisation_id'], unique=False)
    op.create_index('idx_call_metrics_outcome', 'call_metrics', ['call_outcome'], unique=False)
    op.create_table('call_states',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('call_session_id', sa.Integer(), nullable=False),
    sa.Column('state', sa.Enum('INCOMING', 'GREETING', 'PROFILING', 'PROBLEM', 'ADVISORY', 'ESCALATED', 'CLOSURE', 'ENDED', name='statetype'), nullable=False),
    sa.Column('entered_at', sa.DateTime(), nullable=False),
    sa.Column('exited_at', sa.DateTime(), nullable=True),
    sa.Column('state_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['call_session_id'], ['call_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_call_states_session', 'call_states', ['call_session_id'], unique=False)
    op.create_index('idx_call_states_state', 'call_states', ['state'], unique=False)
    op.create_table('call_summaries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('call_session_id', sa.Integer(), nullable=False),
    sa.Column('summary_text_hindi', sa.Text(), nullable=False),
    sa.Column('summary_text_english', sa.Text(), nullable=True),
    sa.Column('key_recommendations', sa.JSON(), nullable=True),
    sa.Column('products_mentioned', sa.JSON(), nullable=True),
    sa.Column('sms_sent', sa.Boolean(), nullable=True),
    sa.Column('sms_sent_at', sa.DateTime(), nullable=True),
    sa.Column('whatsapp_sent', sa.Boolean(), nullable=True),
    sa.Column('whatsapp_sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['call_session_id'], ['call_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_call_summaries_call', 'call_summaries', ['call_session_id'], unique=False)
    op.create_table('call_transcripts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('call_session_id', sa.Integer(), nullable=False),
    sa.Column('speaker', sa.Enum('AI', 'FARMER', 'EXPERT', name='speaker'), nullable=False),
    sa.Column('transcript_text', sa.Text(), nullable=False),
    sa.Column('language_code', sa.String(length=10), nullable=True),
    sa.Column('audio_duration_ms', sa.Integer(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('spoken_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['call_session_id'], ['call_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_transcripts_call', 'call_transcripts', ['call_session_id'], unique=False)
    op.create_index('idx_transcripts_speaker', 'call_transcripts', ['speaker'], unique=False)
    op.create_table('cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('farmer_id', sa.Integer(), nullable=False),
    sa.Column('problem_text', sa.Text(), nullable=False),
    sa.Column('problem_category', sa.String(length=100), nullable=True),
    sa.Column('crop_name', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'RESOLVED', 'ESCALATED', name='casestatus'), nullable=True),
    sa.Column('confidence_score', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['call_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cases_id'), 'cases', ['id'], unique=False)
    op.create_table('farmer_queries',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('call_session_id', sa.BigInteger(), nullable=False),
    sa.Column('farmer_id', sa.BigInteger(), nullable=True),
    sa.Column('organisation_id', sa.BigInteger(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('intent', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['call_session_id'], ['call_sessions.id'], ),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_call_session_id', 'farmer_queries', ['call_session_id'], unique=False)
    op.create_index('ix_farmer_id', 'farmer_queries', ['farmer_id'], unique=False)
    op.create_index('ix_organisation_id', 'farmer_queries', ['organisation_id'], unique=False)
    op.create_table('farmer_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farmer_id', sa.Integer(), nullable=False),
    sa.Column('call_sid', sa.String(length=64), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_farmer_questions_id'), 'farmer_questions', ['id'], unique=False)
    op.execute('CREATE EXTENSION IF NOT EXISTS vector;')
    op.create_table('knowledge_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('crop', sa.String(length=100), nullable=True),
    sa.Column('problem_type', sa.String(length=100), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_entries_company_id'), 'knowledge_entries', ['company_id'], unique=False)
    op.create_index(op.f('ix_knowledge_entries_crop'), 'knowledge_entries', ['crop'], unique=False)
    op.create_index(op.f('ix_knowledge_entries_id'), 'knowledge_entries', ['id'], unique=False)
    op.create_index(op.f('ix_knowledge_entries_organisation_id'), 'knowledge_entries', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_knowledge_entries_problem_type'), 'knowledge_entries', ['problem_type'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('hashed_password', sa.String(length=500), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('organisation_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('advisories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('advisory_text_hindi', sa.Text(), nullable=False),
    sa.Column('advisory_text_english', sa.Text(), nullable=True),
    sa.Column('immediate_action', sa.Text(), nullable=True),
    sa.Column('next_48_hours', sa.Text(), nullable=True),
    sa.Column('preventive_measures', sa.Text(), nullable=True),
    sa.Column('kb_entry_ids', sa.Text(), nullable=True),
    sa.Column('was_escalated', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_advisories_id'), 'advisories', ['id'], unique=False)
    op.create_table('escalations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('confidence_score', sa.String(length=10), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'IN_REVIEW', 'RESOLVED', 'REJECTED', name='escalationstatus'), nullable=True),
    sa.Column('assigned_to', sa.String(length=100), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_escalations_id'), 'escalations', ['id'], unique=False)
    op.create_table('organisation_kb_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=20), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organisation_kb_files_id'), 'organisation_kb_files', ['id'], unique=False)
    op.create_index(op.f('ix_organisation_kb_files_organisation_id'), 'organisation_kb_files', ['organisation_id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('brand_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('sub_category', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('target_crops', sa.Text(), nullable=True),
    sa.Column('target_problems', sa.Text(), nullable=True),
    sa.Column('dosage', sa.Text(), nullable=True),
    sa.Column('usage_instructions', sa.Text(), nullable=True),
    sa.Column('safety_precautions', sa.Text(), nullable=True),
    sa.Column('price_range', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_company_id'), 'products', ['company_id'], unique=False)
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_index(op.f('ix_products_organisation_id'), 'products', ['organisation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_organisation_id'), table_name='products')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_index(op.f('ix_products_company_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_organisation_kb_files_organisation_id'), table_name='organisation_kb_files')
    op.drop_index(op.f('ix_organisation_kb_files_id'), table_name='organisation_kb_files')
    op.drop_table('organisation_kb_files')
    op.drop_index(op.f('ix_escalations_id'), table_name='escalations')
    op.drop_table('escalations')
    op.drop_index(op.f('ix_advisories_id'), table_name='advisories')
    op.drop_table('advisories')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_knowledge_entries_problem_type'), table_name='knowledge_entries')
    op.drop_index(op.f('ix_knowledge_entries_organisation_id'), table_name='knowledge_entries')
    op.drop_index(op.f('ix_knowledge_entries_id'), table_name='knowledge_entries')
    op.drop_index(op.f('ix_knowledge_entries_crop'), table_name='knowledge_entries')
    op.drop_index(op.f('ix_knowledge_entries_company_id'), table_name='knowledge_entries')
    op.drop_table('knowledge_entries')
    op.drop_index(op.f('ix_farmer_questions_id'), table_name='farmer_questions')
    op.drop_table('farmer_questions')
    op.drop_index('ix_organisation_id', table_name='farmer_queries')
    op.drop_index('ix_farmer_id', table_name='farmer_queries')
    op.drop_index('ix_call_session_id', table_name='farmer_queries')
    op.drop_table('farmer_queries')
    op.drop_index(op.f('ix_cases_id'), table_name='cases')
    op.drop_table('cases')
    op.drop_index('idx_transcripts_speaker', table_name='call_transcripts')
    op.drop_index('idx_transcripts_call', table_name='call_transcripts')
    op.drop_table('call_transcripts')
    op.drop_index('idx_call_summaries_call', table_name='call_summaries')
    op.drop_table('call_summaries')
    op.drop_index('idx_call_states_state', table_name='call_states')
    op.drop_index('idx_call_states_session', table_name='call_states')
    op.drop_table('call_states')
    op.drop_index('idx_call_metrics_outcome', table_name='call_metrics')
    op.drop_index('idx_call_metrics_org', table_name='call_metrics')
    op.drop_index('idx_call_metrics_call', table_name='call_metrics')
    op.drop_table('call_metrics')
    op.drop_index(op.f('ix_brands_organisation_id'), table_name='brands')
    op.drop_index(op.f('ix_brands_id'), table_name='brands')
    op.drop_index(op.f('ix_brands_company_id'), table_name='brands')
    op.drop_table('brands')
    op.drop_index(op.f('ix_organisation_phone_numbers_phone_number'), table_name='organisation_phone_numbers')
    op.drop_index(op.f('ix_organisation_phone_numbers_organisation_id'), table_name='organisation_phone_numbers')
    op.drop_index(op.f('ix_organisation_phone_numbers_id'), table_name='organisation_phone_numbers')
    op.drop_index('idx_phone_active_lookup', table_name='organisation_phone_numbers')
    op.drop_table('organisation_phone_numbers')
    op.drop_index(op.f('ix_kb_entries_organisation_id'), table_name='kb_entries')
    op.drop_index(op.f('ix_kb_entries_id'), table_name='kb_entries')
    op.drop_table('kb_entries')
    op.drop_index(op.f('ix_companies_organisation_id'), table_name='companies')
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.drop_table('companies')
    op.drop_index(op.f('ix_call_sessions_session_id'), table_name='call_sessions')
    op.drop_index(op.f('ix_call_sessions_id'), table_name='call_sessions')
    op.drop_table('call_sessions')
    op.drop_table('platform_config')
    op.drop_index(op.f('ix_organisations_id'), table_name='organisations')
    op.drop_table('organisations')
    op.drop_index(op.f('ix_farmers_phone_number'), table_name='farmers')
    op.drop_index(op.f('ix_farmers_id'), table_name='farmers')
    op.drop_table('farmers')
    op.drop_index(op.f('ix_banned_products_product_name'), table_name='banned_products')
    op.drop_index(op.f('ix_banned_products_id'), table_name='banned_products')
    op.drop_table('banned_products')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_organisation_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action_category'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
