"""Add multi-tenant company model

Revision ID: 892e1e494d3f
Revises: add_org_phone_002
Create Date: 2026-01-16 09:46:30.691336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '892e1e494d3f'
down_revision: Union[str, Sequence[str], None] = 'add_org_phone_002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('business_type', sa.String(length=100), nullable=True),
    sa.Column('brand_name', sa.String(length=200), nullable=True),
    sa.Column('contact_person', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('gst_number', sa.String(length=50), nullable=True),
    sa.Column('registration_number', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('max_operators', sa.Integer(), nullable=True),
    sa.Column('max_products', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    op.create_index(op.f('ix_companies_organisation_id'), 'companies', ['organisation_id'], unique=False)
    op.drop_index(op.f('idx_call_summaries_call'), table_name='call_summaries')
    op.drop_table('call_summaries')
    op.drop_index(op.f('idx_audit_category'), table_name='audit_logs')
    op.drop_index(op.f('idx_audit_severity'), table_name='audit_logs')
    op.drop_index(op.f('idx_audit_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('idx_audit_user'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('organisation_id'), table_name='organisation_settings')
    op.drop_table('organisation_settings')
    op.drop_index(op.f('idx_confidence_rules_org'), table_name='confidence_rules')
    op.drop_table('confidence_rules')
    op.drop_index(op.f('idx_transcripts_call'), table_name='call_transcripts')
    op.drop_index(op.f('idx_transcripts_speaker'), table_name='call_transcripts')
    op.drop_table('call_transcripts')
    op.drop_index(op.f('idx_expert_actions_escalation'), table_name='expert_actions')
    op.drop_index(op.f('idx_expert_actions_expert'), table_name='expert_actions')
    op.drop_table('expert_actions')
    op.drop_index(op.f('idx_call_metrics_call'), table_name='call_metrics')
    op.drop_index(op.f('idx_call_metrics_org'), table_name='call_metrics')
    op.drop_index(op.f('idx_call_metrics_outcome'), table_name='call_metrics')
    op.drop_table('call_metrics')
    op.drop_table('platform_config')
    op.drop_index(op.f('idx_banned_active'), table_name='banned_products')
    op.drop_index(op.f('idx_banned_product_name'), table_name='banned_products')
    op.drop_table('banned_products')
    op.drop_index(op.f('idx_brands_org_id'), table_name='brands')
    op.create_index(op.f('ix_brands_id'), 'brands', ['id'], unique=False)
    op.create_index(op.f('ix_brands_organisation_id'), 'brands', ['organisation_id'], unique=False)
    op.drop_index(op.f('idx_call_sessions_org_id'), table_name='call_sessions')
    op.drop_constraint(op.f('call_sessions_ibfk_2'), 'call_sessions', type_='foreignkey')
    op.drop_column('call_sessions', 'organisation_id')
    op.drop_constraint(op.f('cases_ibfk_3'), 'cases', type_='foreignkey')
    op.drop_column('cases', 'affected_area_acres')
    op.drop_column('cases', 'organisation_id')
    op.drop_column('cases', 'crop_stage')
    op.drop_constraint(op.f('escalations_ibfk_2'), 'escalations', type_='foreignkey')
    op.drop_column('escalations', 'organisation_id')
    op.drop_index(op.f('idx_farmers_org_id'), table_name='farmers')
    op.drop_constraint(op.f('farmers_ibfk_1'), 'farmers', type_='foreignkey')
    op.drop_column('farmers', 'organisation_id')
    op.drop_index(op.f('idx_kb_entries_org_id'), table_name='kb_entries')
    op.drop_constraint(op.f('kb_entries_ibfk_1'), 'kb_entries', type_='foreignkey')
    op.drop_column('kb_entries', 'embedding_model')
    op.drop_column('kb_entries', 'embedding_id')
    op.drop_column('kb_entries', 'organisation_id')
    op.drop_column('kb_entries', 'last_embedded_at')
    op.alter_column('organisation_phone_numbers', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='Active phone numbers can receive calls',
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('organisation_phone_numbers', 'display_name',
               existing_type=mysql.VARCHAR(length=100),
               comment=None,
               existing_comment='Friendly name like "Main Helpline" or "Kerala Office"',
               existing_nullable=True)
    op.alter_column('organisation_phone_numbers', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='Last updated timestamp',
               existing_nullable=True)
    op.drop_index(op.f('phone_number'), table_name='organisation_phone_numbers')
    op.create_index(op.f('ix_organisation_phone_numbers_id'), 'organisation_phone_numbers', ['id'], unique=False)
    op.create_index(op.f('ix_organisation_phone_numbers_organisation_id'), 'organisation_phone_numbers', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_organisation_phone_numbers_phone_number'), 'organisation_phone_numbers', ['phone_number'], unique=True)
    op.alter_column('organisations', 'greeting_message',
               existing_type=mysql.TEXT(),
               comment=None,
               existing_comment='Custom AI greeting message for this organisation',
               existing_nullable=True)
    op.alter_column('organisations', 'preferred_languages',
               existing_type=mysql.VARCHAR(length=100),
               comment=None,
               existing_comment='Comma-separated list of languages: hi,en,mr,ta,te,kn,gu,pa,or,bn',
               existing_nullable=False,
               existing_server_default=sa.text("'hi'"))
    op.drop_index(op.f('idx_org_primary_phone'), table_name='organisations')
    op.drop_index(op.f('primary_phone'), table_name='organisations')
    op.create_index(op.f('ix_organisations_id'), 'organisations', ['id'], unique=False)
    op.create_index(op.f('ix_organisations_primary_phone'), 'organisations', ['primary_phone'], unique=True)
    op.add_column('products', sa.Column('company_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('idx_products_org_id'), table_name='products')
    op.create_index(op.f('ix_products_company_id'), 'products', ['company_id'], unique=False)
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_index(op.f('ix_products_organisation_id'), 'products', ['organisation_id'], unique=False)
    op.create_foreign_key(None, 'products', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.drop_column('products', 'approval_status')
    op.drop_column('products', 'approved_by')
    op.drop_column('products', 'ban_reason')
    op.drop_column('products', 'approved_at')
    op.add_column('users', sa.Column('company_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('idx_users_org_id'), table_name='users')
    op.drop_constraint(op.f('users_ibfk_1'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'companies', ['company_id'], ['id'])
    op.create_foreign_key(None, 'users', 'organisations', ['organisation_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(op.f('users_ibfk_1'), 'users', 'organisations', ['organisation_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('idx_users_org_id'), 'users', ['organisation_id'], unique=False)
    op.drop_column('users', 'company_id')
    op.add_column('products', sa.Column('approved_at', mysql.DATETIME(), nullable=True))
    op.add_column('products', sa.Column('ban_reason', mysql.TEXT(), nullable=True))
    op.add_column('products', sa.Column('approved_by', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('approval_status', mysql.ENUM('pending', 'approved', 'banned'), server_default=sa.text("'pending'"), nullable=True))
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_index(op.f('ix_products_organisation_id'), table_name='products')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_index(op.f('ix_products_company_id'), table_name='products')
    op.create_index(op.f('idx_products_org_id'), 'products', ['organisation_id'], unique=False)
    op.drop_column('products', 'company_id')
    op.drop_index(op.f('ix_organisations_primary_phone'), table_name='organisations')
    op.drop_index(op.f('ix_organisations_id'), table_name='organisations')
    op.create_index(op.f('primary_phone'), 'organisations', ['primary_phone'], unique=True)
    op.create_index(op.f('idx_org_primary_phone'), 'organisations', ['primary_phone'], unique=False)
    op.alter_column('organisations', 'preferred_languages',
               existing_type=mysql.VARCHAR(length=100),
               comment='Comma-separated list of languages: hi,en,mr,ta,te,kn,gu,pa,or,bn',
               existing_nullable=False,
               existing_server_default=sa.text("'hi'"))
    op.alter_column('organisations', 'greeting_message',
               existing_type=mysql.TEXT(),
               comment='Custom AI greeting message for this organisation',
               existing_nullable=True)
    op.drop_index(op.f('ix_organisation_phone_numbers_phone_number'), table_name='organisation_phone_numbers')
    op.drop_index(op.f('ix_organisation_phone_numbers_organisation_id'), table_name='organisation_phone_numbers')
    op.drop_index(op.f('ix_organisation_phone_numbers_id'), table_name='organisation_phone_numbers')
    op.create_index(op.f('phone_number'), 'organisation_phone_numbers', ['phone_number'], unique=True)
    op.alter_column('organisation_phone_numbers', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment='Last updated timestamp',
               existing_nullable=True)
    op.alter_column('organisation_phone_numbers', 'display_name',
               existing_type=mysql.VARCHAR(length=100),
               comment='Friendly name like "Main Helpline" or "Kerala Office"',
               existing_nullable=True)
    op.alter_column('organisation_phone_numbers', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               comment='Active phone numbers can receive calls',
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
    op.add_column('kb_entries', sa.Column('last_embedded_at', mysql.DATETIME(), nullable=True))
    op.add_column('kb_entries', sa.Column('organisation_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('kb_entries', sa.Column('embedding_id', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('kb_entries', sa.Column('embedding_model', mysql.VARCHAR(length=100), nullable=True))
    op.create_foreign_key(op.f('kb_entries_ibfk_1'), 'kb_entries', 'organisations', ['organisation_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_kb_entries_org_id'), 'kb_entries', ['organisation_id'], unique=False)
    op.add_column('farmers', sa.Column('organisation_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('farmers_ibfk_1'), 'farmers', 'organisations', ['organisation_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_farmers_org_id'), 'farmers', ['organisation_id'], unique=False)
    op.add_column('escalations', sa.Column('organisation_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('escalations_ibfk_2'), 'escalations', 'organisations', ['organisation_id'], ['id'], ondelete='CASCADE')
    op.add_column('cases', sa.Column('crop_stage', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('cases', sa.Column('organisation_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('cases', sa.Column('affected_area_acres', mysql.FLOAT(), nullable=True))
    op.create_foreign_key(op.f('cases_ibfk_3'), 'cases', 'organisations', ['organisation_id'], ['id'], ondelete='CASCADE')
    op.add_column('call_sessions', sa.Column('organisation_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('call_sessions_ibfk_2'), 'call_sessions', 'organisations', ['organisation_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_call_sessions_org_id'), 'call_sessions', ['organisation_id'], unique=False)
    op.drop_index(op.f('ix_brands_organisation_id'), table_name='brands')
    op.drop_index(op.f('ix_brands_id'), table_name='brands')
    op.create_index(op.f('idx_brands_org_id'), 'brands', ['organisation_id'], unique=False)
    op.create_table('banned_products',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('product_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=False),
    sa.Column('chemical_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=True),
    sa.Column('ban_reason', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('regulatory_reference', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('banned_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('banned_by_user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('expiry_date', sa.DATE(), nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=False),
    sa.Column('extra_data', mysql.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['banned_by_user_id'], ['users.id'], name=op.f('banned_products_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('idx_banned_product_name'), 'banned_products', ['product_name'], unique=False)
    op.create_index(op.f('idx_banned_active'), 'banned_products', ['is_active'], unique=False)
    op.create_table('platform_config',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ai_confidence_threshold', mysql.FLOAT(), server_default=sa.text("'0.7'"), nullable=False),
    sa.Column('max_call_duration_minutes', mysql.INTEGER(), server_default=sa.text("'30'"), autoincrement=False, nullable=False),
    sa.Column('default_language', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), server_default=sa.text("'hi'"), nullable=False),
    sa.Column('stt_provider', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), server_default=sa.text("'google'"), nullable=False),
    sa.Column('tts_provider', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), server_default=sa.text("'google'"), nullable=False),
    sa.Column('llm_model', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), server_default=sa.text("'gpt-4'"), nullable=False),
    sa.Column('rag_enabled', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=False),
    sa.Column('rag_top_k', mysql.INTEGER(), server_default=sa.text("'5'"), autoincrement=False, nullable=False),
    sa.Column('enable_product_safety_check', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=False),
    sa.Column('auto_escalate_low_confidence', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=False),
    sa.Column('min_confidence_for_product_recommendation', mysql.FLOAT(), server_default=sa.text("'0.8'"), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_by_user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name=op.f('platform_config_ibfk_1'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('call_metrics',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('call_session_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('organisation_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_duration_seconds', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('states_visited', mysql.JSON(), nullable=True),
    sa.Column('profiling_questions_completed', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('symptoms_detected', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('kb_entries_retrieved', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('advisory_confidence', mysql.FLOAT(), nullable=True),
    sa.Column('was_escalated', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('escalation_reason', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('farmer_satisfaction', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('call_outcome', mysql.ENUM('COMPLETED', 'ABANDONED', 'ESCALATED', 'FAILED', 'CALLBACK_SCHEDULED'), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.ForeignKeyConstraint(['call_session_id'], ['call_sessions.id'], name=op.f('call_metrics_ibfk_1'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], name=op.f('call_metrics_ibfk_2'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('idx_call_metrics_outcome'), 'call_metrics', ['call_outcome'], unique=False)
    op.create_index(op.f('idx_call_metrics_org'), 'call_metrics', ['organisation_id'], unique=False)
    op.create_index(op.f('idx_call_metrics_call'), 'call_metrics', ['call_session_id'], unique=False)
    op.create_table('expert_actions',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('escalation_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('expert_user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('action_type', mysql.ENUM('VIEWED', 'ASSIGNED', 'NOTES_ADDED', 'ADVISORY_PROVIDED', 'CALLBACK_SCHEDULED', 'RESOLVED', 'REOPENED'), nullable=False),
    sa.Column('action_notes', mysql.TEXT(), nullable=True),
    sa.Column('time_spent_seconds', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.ForeignKeyConstraint(['escalation_id'], ['escalations.id'], name=op.f('expert_actions_ibfk_1'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['expert_user_id'], ['users.id'], name=op.f('expert_actions_ibfk_2'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('idx_expert_actions_expert'), 'expert_actions', ['expert_user_id'], unique=False)
    op.create_index(op.f('idx_expert_actions_escalation'), 'expert_actions', ['escalation_id'], unique=False)
    op.create_table('call_transcripts',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('call_session_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('speaker', mysql.ENUM('AI', 'FARMER', 'EXPERT'), nullable=False),
    sa.Column('transcript_text', mysql.TEXT(), nullable=False),
    sa.Column('language_code', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('audio_duration_ms', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('confidence_score', mysql.FLOAT(), nullable=True),
    sa.Column('spoken_at', mysql.DATETIME(), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.ForeignKeyConstraint(['call_session_id'], ['call_sessions.id'], name=op.f('call_transcripts_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('idx_transcripts_speaker'), 'call_transcripts', ['speaker'], unique=False)
    op.create_index(op.f('idx_transcripts_call'), 'call_transcripts', ['call_session_id'], unique=False)
    op.create_table('confidence_rules',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('organisation_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rule_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('rule_type', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('threshold_value', mysql.FLOAT(), nullable=True),
    sa.Column('escalation_reason', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('priority_boost', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], name=op.f('confidence_rules_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('idx_confidence_rules_org'), 'confidence_rules', ['organisation_id'], unique=False)
    op.create_table('organisation_settings',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('organisation_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ai_model', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('default_language', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('supported_languages', mysql.TEXT(), nullable=True),
    sa.Column('crop_focus', mysql.TEXT(), nullable=True),
    sa.Column('monthly_call_limit', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('features_enabled', mysql.TEXT(), nullable=True),
    sa.Column('ai_prompt_template', mysql.TEXT(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], name=op.f('organisation_settings_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('organisation_id'), 'organisation_settings', ['organisation_id'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('action_type', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('action_category', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False),
    sa.Column('entity_type', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('entity_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('old_value', mysql.JSON(), nullable=True),
    sa.Column('new_value', mysql.JSON(), nullable=True),
    sa.Column('ip_address', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=45), nullable=True),
    sa.Column('user_agent', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('severity', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), server_default=sa.text("'info'"), nullable=False),
    sa.Column('timestamp', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('extra_data', mysql.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('audit_logs_ibfk_1'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('idx_audit_user'), 'audit_logs', ['user_id'], unique=False)
    op.create_index(op.f('idx_audit_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_index(op.f('idx_audit_severity'), 'audit_logs', ['severity'], unique=False)
    op.create_index(op.f('idx_audit_category'), 'audit_logs', ['action_category'], unique=False)
    op.create_table('call_summaries',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('call_session_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('summary_text_hindi', mysql.TEXT(), nullable=False),
    sa.Column('summary_text_english', mysql.TEXT(), nullable=True),
    sa.Column('key_recommendations', mysql.JSON(), nullable=True),
    sa.Column('products_mentioned', mysql.JSON(), nullable=True),
    sa.Column('sms_sent', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('sms_sent_at', mysql.DATETIME(), nullable=True),
    sa.Column('whatsapp_sent', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('whatsapp_sent_at', mysql.DATETIME(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.ForeignKeyConstraint(['call_session_id'], ['call_sessions.id'], name=op.f('call_summaries_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('idx_call_summaries_call'), 'call_summaries', ['call_session_id'], unique=False)
    op.drop_index(op.f('ix_companies_organisation_id'), table_name='companies')
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
