"""enable_cascade_delete_users

Revision ID: f26eb22b3f29
Revises: 2f680dd243b0
Create Date: 2026-03-10 10:30:20.486711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f26eb22b3f29'
down_revision: Union[str, Sequence[str], None] = '2f680dd243b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'embedding')
    op.drop_constraint(op.f('users_company_id_fkey'), 'users', type_='foreignkey')
    op.drop_constraint(op.f('users_organisation_id_fkey'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'organisations', ['organisation_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'users', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(op.f('users_organisation_id_fkey'), 'users', 'organisations', ['organisation_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('users_company_id_fkey'), 'users', 'companies', ['company_id'], ['id'], ondelete='SET NULL')
    op.add_column('products', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
